### ISSUE TITLE
Cast exception in Content lookup operation between two LAN computers

### ISSUE THREAD

**Issue by orneo1212** [JoshuaKissoon/Kademlia#11]
Below exception

Exception in thread "Thread-1" java.lang.ClassCastException:
kademlia.message.ContentLookupMessage cannot be cast to
kademlia.message.NodeReplyMessage
    at kademlia.operation.ContentLookupOperation.receive(ContentLookupOperation.java:264)
    at kademlia.KadServer.listen(KadServer.java:264)
    at kademlia.KadServer.access$000(KadServer.java:29)
    at kademlia.KadServer$1.run(KadServer.java:93)

**Comment by orneo1212** [comment]
On localhost setting value by one node can be retrieved by second node
